import { useEffect,useState } from 'react'
import { get } from '@/utils/request'
type Totals={count:number;paid:string;refund:string;net:string}
interface Summary { summary:Totals;trend:(Totals&{date:string})[];details:(Totals&{id:number;order_no:string;status:string;date:string})[];policy:{time_basis:string;amount_basis:string;refund_basis:string} }
export function OperatingSummary(){
 const [start,setStart]=useState(new Date(Date.now()-7*86400000).toLocaleDateString('sv-SE')),[end,setEnd]=useState(new Date(Date.now()+86400000).toLocaleDateString('sv-SE')),[data,setData]=useState<Summary|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{setBusy(true);setError('');setData(null);try{const r=await get<{data:Summary}>('/api/v1/admin/operating-summary?'+new URLSearchParams({start,end,timezone:'Asia/Shanghai'}));setData(r.data)}catch{setError('经营统计加载失败，请检查日期范围')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 return <section className="vben-card p-4 space-y-3"><h2 className="font-semibold">经营对账 · 人民币</h2><div className="flex flex-wrap items-end gap-3"><label>开始<input aria-label="统计开始日期" type="date" className="input-ios" value={start} onChange={e=>setStart(e.target.value)}/></label><label>结束（不含当天）<input aria-label="统计结束日期" type="date" className="input-ios" value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="btn-ios-primary" disabled={busy} onClick={load}>{busy?'加载中':'查询'}</button></div><p className="text-sm text-slate-500">时区：上海；订单数、付款、退款与净额使用同一批明细。账号数量不代表业务可用账号数。</p>{error&&<p role="alert">{error}</p>}{data&&<><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{Object.entries({订单:data.summary.count,付款:data.summary.paid,退款:data.summary.refund,净额:data.summary.net}).map(([k,v])=><div className="rounded bg-slate-100 dark:bg-slate-800 p-3" key={k}><p>{k}</p><strong className="text-xl tabular-nums">{v}</strong></div>)}</div><p className="text-xs text-slate-500">{data.policy.time_basis}；{data.policy.amount_basis}；{data.policy.refund_basis}</p><div aria-label="每日净额趋势" className="space-y-2">{data.trend.map(t=><div className="flex gap-3 items-center" key={t.date}><span className="text-xs w-24">{t.date}</span><meter className="flex-1" min={0} max={Math.max(1,...data.trend.map(x=>Number(x.net)))} value={Number(t.net)}/><span className="tabular-nums w-24">{t.net}</span></div>)}</div><details><summary>对账明细（{data.details.length}条）</summary><div className="overflow-auto max-h-80"><table className="table-ios"><thead><tr><th>订单</th><th>日期</th><th>状态</th><th>付款</th><th>退款</th><th>净额</th></tr></thead><tbody>{data.details.map(d=><tr key={d.id}><td>{d.order_no}</td><td>{d.date}</td><td>{d.status}</td><td>{d.paid}</td><td>{d.refund}</td><td>{d.net}</td></tr>)}</tbody></table></div></details>{!data.details.length&&<p>此时间窗暂无纳入口径的订单</p>}</>}</section>
}
