import { useEffect, useState } from 'react'
import { get, post, put, del } from '@/utils/request'
interface Template { event_type: string; body: string; variables: Record<string,string> }
interface Delivery { id:string; account_id:string; event_type:string; status:string; attempts:number; merged_count:number }
const base='/api/v1/notification-channels'
const labels: Record<string,string>={accepted:'已受理',not_accepted:'未受理，等待重试',unknown:'待核实，不自动重发',pending:'待投递',sending:'已提交',exhausted:'重试耗尽',cancelled:'渠道停用'}
export function NotificationTemplates() {
  const [templates,setTemplates]=useState<Template[]>([]),[selected,setSelected]=useState('test'),[body,setBody]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState(''),[deliveries,setDeliveries]=useState<Delivery[]>([]),[busy,setBusy]=useState(false)
  const load=async()=>{try{const [t,d]=await Promise.all([get<{data:Template[]}>(base+'/templates'),get<{data:Delivery[]}>(base+'/deliveries')]);setTemplates(t.data);setBody(t.data.find(x=>x.event_type===selected)?.body||'');setDeliveries(d.data)}catch{setMessage('模板或投递记录加载失败')}}
  useEffect(()=>{void load()},[])
  const action=async(kind:string)=>{setBusy(true);setMessage('');try{if(kind==='preview'){const r=await post<{text:string}>(`${base}/templates/${selected}/preview`,{body,variables:{account_id:'预览账号',summary:'示例事件'}});setPreview(r.text)}else{if(kind==='reset')await del(`${base}/templates/${selected}`);else await put(`${base}/templates/${selected}`,{body});setMessage(kind==='reset'?'已恢复选中模板':'已保存');await load()}}catch{setMessage('操作失败，请检查模板变量或格式')}finally{setBusy(false)}}
  return <section className="vben-card p-4 space-y-3"><h2 className="font-semibold">通知模板与投递记录</h2><label className="input-label">事件模板<select className="input-ios" value={selected} onChange={e=>{setSelected(e.target.value);setBody(templates.find(t=>t.event_type===e.target.value)?.body||'');setPreview('')}}>{templates.map(t=><option key={t.event_type}>{t.event_type}</option>)}</select></label><p className="text-sm text-slate-500">变量：{Object.keys(templates.find(t=>t.event_type===selected)?.variables||{}).join("、")}。缺省内容采用提示文案；验证链接指向账号页。渠道测试使用 test 模板。</p><textarea aria-label="模板内容" className="input-ios h-24" value={body} onChange={e=>setBody(e.target.value)}/><div className="flex flex-wrap gap-2"><button disabled={busy} className="btn-ios-secondary" onClick={()=>action('preview')}>预览</button><button disabled={busy} className="btn-ios-primary" onClick={()=>action('save')}>保存</button><button disabled={busy} className="btn-ios-secondary" onClick={()=>action('reset')}>恢复选中模板</button><button disabled={busy} className="btn-ios-secondary" onClick={load}>刷新投递</button></div>{message&&<p role="status">{message}</p>}{preview&&<pre className="whitespace-pre-wrap rounded bg-slate-100 dark:bg-slate-800 p-3">{preview}</pre>}<div className="overflow-x-auto"><table className="table-ios"><thead><tr><th>账号</th><th>事件</th><th>投递状态</th><th>尝试</th><th>合并次数</th></tr></thead><tbody>{deliveries.map(d=><tr key={d.id}><td>{d.account_id}</td><td>{d.event_type}</td><td>{labels[d.status]||d.status}</td><td>{d.attempts}</td><td>{d.merged_count}</td></tr>)}</tbody></table>{!deliveries.length&&<p>暂无投递记录</p>}</div></section>
}
