import { useEffect,useState } from 'react'
import { get,post,del } from '@/utils/request'
interface Data { data:Record<string,unknown>[];columns:string[];count:number;capabilities:{delete:boolean} }
interface Preview { preview_id:string;count:number;related_count:number;owners:number[] }
const tables=[['users','后台用户'],['xy_accounts','闲鱼账号'],['xy_orders','订单'],['xy_catalog_items','商品'],['xy_keyword_rules','回复规则'],['xy_notification_channels','通知渠道'],['xy_message_notifications','通知绑定'],['xy_risk_control_logs','风控日志']]
export function DataManagement(){
 const [table,setTable]=useState('xy_accounts'),[page,setPage]=useState(0),[data,setData]=useState<Data|null>(null),[preview,setPreview]=useState<Preview|null>(null),[confirmation,setConfirmation]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const base='/api/v1/admin/data/'+table
 const load=async()=>{setBusy(true);setMessage('');setData(null);setPreview(null);try{setData(await get<Data>(`${base}?limit=50&offset=${page*50}`))}catch{setMessage('数据加载失败')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[table,page])
 const prepare=async()=>{setBusy(true);setMessage('');try{setPreview(await post<Preview>(base+'/preview'));setConfirmation('')}catch{setMessage('预览失败：请检查此表操作权限')}finally{setBusy(false)}}
 const remove=async()=>{if(!preview)return;setBusy(true);setMessage('');try{await del(base+'?'+new URLSearchParams({preview_id:preview.preview_id,confirmation}));await load();setMessage('已删除并记录审计')}catch{setMessage('删除未执行：需已验证恢复点、有效预览，并输入 DELETE；数据有变化时请重新预览')}finally{setBusy(false)}}
 const exportPage=()=>{if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data.data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${table}-page-${page+1}.json`;a.click();URL.revokeObjectURL(url)}
 return <div className="space-y-4"><section className="vben-card p-4 space-y-3"><h1 className="page-title">白名单数据管理</h1><p className="text-sm text-slate-500">仅开放脱敏数据。业务历史和防重事实只读；通知配置删除先预览关联，且需隔离恢复验证。</p><div className="flex gap-3 flex-wrap"><select aria-label="数据表" className="input-ios max-w-xs" value={table} onChange={e=>{setTable(e.target.value);setPage(0)}}>{tables.map(([v,t])=><option value={v} key={v}>{t}</option>)}</select><button className="btn-ios-secondary" disabled={busy} onClick={load}>刷新</button><button className="btn-ios-secondary" disabled={!data} onClick={exportPage}>导出当前页（脱敏）</button><button className="btn-ios-danger" disabled={busy||!data?.capabilities.delete||!data.count} onClick={prepare}>预览清表影响</button></div>{message&&<p role="alert">{message}</p>}{busy&&<p role="status">加载中…</p>}</section>{preview&&<section className="vben-card p-4 space-y-3 border border-red-300"><h2 className="font-semibold">删除确认 · 5分钟内有效</h2><p>本表 {preview.count} 条；关联绑定 {preview.related_count} 条；所属用户 {preview.owners.join('、')}。</p><p>需已通过隔离恢复验证的备份；任一数据变化都需重新预览。</p><input aria-label="输入DELETE确认" className="input-ios" value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder="输入 DELETE"/><div className="flex gap-2"><button className="btn-ios-danger" disabled={busy||confirmation!=='DELETE'} onClick={remove}>确认原子删除</button><button className="btn-ios-secondary" onClick={()=>setPreview(null)}>取消</button></div></section>}{data&&<section className="vben-card p-4"><p>共 {data.count} 条 · 第 {page+1} 页</p><div className="overflow-x-auto"><table className="table-ios"><thead><tr>{data.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{data.data.map((r,i)=><tr key={String(r.id??i)}>{data.columns.map(c=><td key={c} className="max-w-xs truncate">{r[c]===null?'-':typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??'')}</td>)}</tr>)}</tbody></table>{!data.data.length&&<p className="p-4">此页暂无数据</p>}</div><div className="flex gap-3 mt-3"><button className="btn-ios-secondary" disabled={busy||page===0} onClick={()=>setPage(page-1)}>上一页</button><button className="btn-ios-secondary" disabled={busy||(page+1)*50>=data.count} onClick={()=>setPage(page+1)}>下一页</button></div></section>}</div>
}
